import React from "react";

import type { Metadata } from "next";
import { Geist_Mono, Inter } from "next/font/google";

import RainbowKit from "@/components/RainbowKit/RainbowKit";

import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${geistMono.variable} antialiased`}>
        <RainbowKit>{children}</RainbowKit>
      </body>
    </html>
  );
}
